name: CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  wait-for-setup:
    runs-on: ubuntu-latest
    steps:
    - name: Download setup completion artifact
      id: setup-check
      uses: actions/download-artifact@v3
      with:
        name: ec2-setup-complete
      continue-on-error: true

  test:
    needs: wait-for-setup
    if: needs.wait-for-setup.result == 'success'
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask pytest requests

    - name: Run tests
      run: pytest tests.py

  deploy:
    needs: [wait-for-setup, test]
    if: success()
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Merge dev into main
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git checkout main
        git merge dev
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push to main branch
      run: git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd /home/ubuntu/my-flask-app
          git pull origin main
          pip3 install -r requirements.txt
          sudo systemctl restart my-flask-app.service
