name: Test, Merge, and Deploy

on:
  push:
    branches:
      - dev

jobs:
  test_and_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: dev  # Work with the dev branch

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask pytest requests  # Install dependencies for app and testing

      - name: Run Tests
        run: |
          pytest tests.py  # Run tests on GitHub runner

      - name: Merge to Main if Tests Pass
        if: success()  # Proceed only if tests passed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout main
          git merge dev
          git push origin main

